//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeapproveSuggestionPayload")
public inline fun approveSuggestionPayload(block: com.maloy.proto.ApproveSuggestionPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ApproveSuggestionPayload =
  com.maloy.proto.ApproveSuggestionPayloadKt.Dsl._create(com.maloy.proto.Listentogether.ApproveSuggestionPayload.newBuilder()).apply { block() }._build()
public object ApproveSuggestionPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.ApproveSuggestionPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.ApproveSuggestionPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.ApproveSuggestionPayload = _builder.build()

    /**
     * <code>string suggestion_id = 1;</code>
     */
    public var suggestionId: kotlin.String
      @JvmName("getSuggestionId")
      get() = _builder.getSuggestionId()
      @JvmName("setSuggestionId")
      set(value) {
        _builder.setSuggestionId(value)
      }
    /**
     * <code>string suggestion_id = 1;</code>
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.ApproveSuggestionPayload.copy(block: com.maloy.proto.ApproveSuggestionPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ApproveSuggestionPayload =
  com.maloy.proto.ApproveSuggestionPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

