//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeapproveJoinPayload")
public inline fun approveJoinPayload(block: com.maloy.proto.ApproveJoinPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ApproveJoinPayload =
  com.maloy.proto.ApproveJoinPayloadKt.Dsl._create(com.maloy.proto.Listentogether.ApproveJoinPayload.newBuilder()).apply { block() }._build()
public object ApproveJoinPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.ApproveJoinPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.ApproveJoinPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.ApproveJoinPayload = _builder.build()

    /**
     * <code>string user_id = 1;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 1;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.ApproveJoinPayload.copy(block: com.maloy.proto.ApproveJoinPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ApproveJoinPayload =
  com.maloy.proto.ApproveJoinPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

