//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializebufferCompletePayload")
public inline fun bufferCompletePayload(block: com.maloy.proto.BufferCompletePayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.BufferCompletePayload =
  com.maloy.proto.BufferCompletePayloadKt.Dsl._create(com.maloy.proto.Listentogether.BufferCompletePayload.newBuilder()).apply { block() }._build()
public object BufferCompletePayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.BufferCompletePayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.BufferCompletePayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.BufferCompletePayload = _builder.build()

    /**
     * <code>string track_id = 1;</code>
     */
    public var trackId: kotlin.String
      @JvmName("getTrackId")
      get() = _builder.getTrackId()
      @JvmName("setTrackId")
      set(value) {
        _builder.setTrackId(value)
      }
    /**
     * <code>string track_id = 1;</code>
     */
    public fun clearTrackId() {
      _builder.clearTrackId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.BufferCompletePayload.copy(block: com.maloy.proto.BufferCompletePayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.BufferCompletePayload =
  com.maloy.proto.BufferCompletePayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

