//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializebufferWaitPayload")
public inline fun bufferWaitPayload(block: com.maloy.proto.BufferWaitPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.BufferWaitPayload =
  com.maloy.proto.BufferWaitPayloadKt.Dsl._create(com.maloy.proto.Listentogether.BufferWaitPayload.newBuilder()).apply { block() }._build()
public object BufferWaitPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.BufferWaitPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.BufferWaitPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.BufferWaitPayload = _builder.build()

    /**
     * <code>string track_id = 1;</code>
     */
    public var trackId: kotlin.String
      @JvmName("getTrackId")
      get() = _builder.getTrackId()
      @JvmName("setTrackId")
      set(value) {
        _builder.setTrackId(value)
      }
    /**
     * <code>string track_id = 1;</code>
     */
    public fun clearTrackId() {
      _builder.clearTrackId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WaitingForProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @return A list containing the waitingFor.
     */
    public val waitingFor: com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getWaitingForList()
      )
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param value The waitingFor to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addWaitingFor")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.add(value: kotlin.String) {
      _builder.addWaitingFor(value)
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param value The waitingFor to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignWaitingFor")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param values The waitingFor to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllWaitingFor")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllWaitingFor(values)
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param values The waitingFor to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllWaitingFor")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param index The index to set the value at.
     * @param value The waitingFor to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setWaitingFor")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setWaitingFor(index, value)
    }/**
     * <code>repeated string waiting_for = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearWaitingFor")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WaitingForProxy>.clear() {
      _builder.clearWaitingFor()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.BufferWaitPayload.copy(block: com.maloy.proto.BufferWaitPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.BufferWaitPayload =
  com.maloy.proto.BufferWaitPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

