//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeclientCapabilities")
public inline fun clientCapabilities(block: com.maloy.proto.ClientCapabilitiesKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ClientCapabilities =
  com.maloy.proto.ClientCapabilitiesKt.Dsl._create(com.maloy.proto.Listentogether.ClientCapabilities.newBuilder()).apply { block() }._build()
public object ClientCapabilitiesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.ClientCapabilities.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.ClientCapabilities.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.ClientCapabilities = _builder.build()

    /**
     * <code>bool supports_protobuf = 1;</code>
     */
    public var supportsProtobuf: kotlin.Boolean
      @JvmName("getSupportsProtobuf")
      get() = _builder.getSupportsProtobuf()
      @JvmName("setSupportsProtobuf")
      set(value) {
        _builder.setSupportsProtobuf(value)
      }
    /**
     * <code>bool supports_protobuf = 1;</code>
     */
    public fun clearSupportsProtobuf() {
      _builder.clearSupportsProtobuf()
    }

    /**
     * <code>bool supports_compression = 2;</code>
     */
    public var supportsCompression: kotlin.Boolean
      @JvmName("getSupportsCompression")
      get() = _builder.getSupportsCompression()
      @JvmName("setSupportsCompression")
      set(value) {
        _builder.setSupportsCompression(value)
      }
    /**
     * <code>bool supports_compression = 2;</code>
     */
    public fun clearSupportsCompression() {
      _builder.clearSupportsCompression()
    }

    /**
     * <code>string client_version = 3;</code>
     */
    public var clientVersion: kotlin.String
      @JvmName("getClientVersion")
      get() = _builder.getClientVersion()
      @JvmName("setClientVersion")
      set(value) {
        _builder.setClientVersion(value)
      }
    /**
     * <code>string client_version = 3;</code>
     */
    public fun clearClientVersion() {
      _builder.clearClientVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.ClientCapabilities.copy(block: com.maloy.proto.ClientCapabilitiesKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ClientCapabilities =
  com.maloy.proto.ClientCapabilitiesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

