//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializecreateRoomPayload")
public inline fun createRoomPayload(block: com.maloy.proto.CreateRoomPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.CreateRoomPayload =
  com.maloy.proto.CreateRoomPayloadKt.Dsl._create(com.maloy.proto.Listentogether.CreateRoomPayload.newBuilder()).apply { block() }._build()
public object CreateRoomPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.CreateRoomPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.CreateRoomPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.CreateRoomPayload = _builder.build()

    /**
     * <code>string username = 1;</code>
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * <code>string username = 1;</code>
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.CreateRoomPayload.copy(block: com.maloy.proto.CreateRoomPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.CreateRoomPayload =
  com.maloy.proto.CreateRoomPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

