//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeenvelope")
public inline fun envelope(block: com.maloy.proto.EnvelopeKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.Envelope =
  com.maloy.proto.EnvelopeKt.Dsl._create(com.maloy.proto.Listentogether.Envelope.newBuilder()).apply { block() }._build()
public object EnvelopeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.Envelope.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.Envelope.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.Envelope = _builder.build()

    /**
     * <code>string type = 1;</code>
     */
    public var type: kotlin.String
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>string type = 1;</code>
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * <code>bytes payload = 2;</code>
     */
    public var payload: com.google.protobuf.ByteString
      @JvmName("getPayload")
      get() = _builder.getPayload()
      @JvmName("setPayload")
      set(value) {
        _builder.setPayload(value)
      }
    /**
     * <code>bytes payload = 2;</code>
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * <pre>
     * Indicates if payload is gzip compressed
     * </pre>
     *
     * <code>bool compressed = 3;</code>
     */
    public var compressed: kotlin.Boolean
      @JvmName("getCompressed")
      get() = _builder.getCompressed()
      @JvmName("setCompressed")
      set(value) {
        _builder.setCompressed(value)
      }
    /**
     * <pre>
     * Indicates if payload is gzip compressed
     * </pre>
     *
     * <code>bool compressed = 3;</code>
     */
    public fun clearCompressed() {
      _builder.clearCompressed()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.Envelope.copy(block: com.maloy.proto.EnvelopeKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.Envelope =
  com.maloy.proto.EnvelopeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

