//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeerrorPayload")
public inline fun errorPayload(block: com.maloy.proto.ErrorPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ErrorPayload =
  com.maloy.proto.ErrorPayloadKt.Dsl._create(com.maloy.proto.Listentogether.ErrorPayload.newBuilder()).apply { block() }._build()
public object ErrorPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.ErrorPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.ErrorPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.ErrorPayload = _builder.build()

    /**
     * <code>string code = 1;</code>
     */
    public var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * <code>string code = 1;</code>
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * <code>string message = 2;</code>
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 2;</code>
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.ErrorPayload.copy(block: com.maloy.proto.ErrorPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ErrorPayload =
  com.maloy.proto.ErrorPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

