//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializehostChangedPayload")
public inline fun hostChangedPayload(block: com.maloy.proto.HostChangedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.HostChangedPayload =
  com.maloy.proto.HostChangedPayloadKt.Dsl._create(com.maloy.proto.Listentogether.HostChangedPayload.newBuilder()).apply { block() }._build()
public object HostChangedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.HostChangedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.HostChangedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.HostChangedPayload = _builder.build()

    /**
     * <code>string new_host_id = 1;</code>
     */
    public var newHostId: kotlin.String
      @JvmName("getNewHostId")
      get() = _builder.getNewHostId()
      @JvmName("setNewHostId")
      set(value) {
        _builder.setNewHostId(value)
      }
    /**
     * <code>string new_host_id = 1;</code>
     */
    public fun clearNewHostId() {
      _builder.clearNewHostId()
    }

    /**
     * <code>string new_host_name = 2;</code>
     */
    public var newHostName: kotlin.String
      @JvmName("getNewHostName")
      get() = _builder.getNewHostName()
      @JvmName("setNewHostName")
      set(value) {
        _builder.setNewHostName(value)
      }
    /**
     * <code>string new_host_name = 2;</code>
     */
    public fun clearNewHostName() {
      _builder.clearNewHostName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.HostChangedPayload.copy(block: com.maloy.proto.HostChangedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.HostChangedPayload =
  com.maloy.proto.HostChangedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

