//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializejoinRoomPayload")
public inline fun joinRoomPayload(block: com.maloy.proto.JoinRoomPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.JoinRoomPayload =
  com.maloy.proto.JoinRoomPayloadKt.Dsl._create(com.maloy.proto.Listentogether.JoinRoomPayload.newBuilder()).apply { block() }._build()
public object JoinRoomPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.JoinRoomPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.JoinRoomPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.JoinRoomPayload = _builder.build()

    /**
     * <code>string room_code = 1;</code>
     */
    public var roomCode: kotlin.String
      @JvmName("getRoomCode")
      get() = _builder.getRoomCode()
      @JvmName("setRoomCode")
      set(value) {
        _builder.setRoomCode(value)
      }
    /**
     * <code>string room_code = 1;</code>
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * <code>string username = 2;</code>
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * <code>string username = 2;</code>
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.JoinRoomPayload.copy(block: com.maloy.proto.JoinRoomPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.JoinRoomPayload =
  com.maloy.proto.JoinRoomPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

