//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializekickedPayload")
public inline fun kickedPayload(block: com.maloy.proto.KickedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.KickedPayload =
  com.maloy.proto.KickedPayloadKt.Dsl._create(com.maloy.proto.Listentogether.KickedPayload.newBuilder()).apply { block() }._build()
public object KickedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.KickedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.KickedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.KickedPayload = _builder.build()

    /**
     * <code>string reason = 1;</code>
     */
    public var reason: kotlin.String
      @JvmName("getReason")
      get() = _builder.getReason()
      @JvmName("setReason")
      set(value) {
        _builder.setReason(value)
      }
    /**
     * <code>string reason = 1;</code>
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.KickedPayload.copy(block: com.maloy.proto.KickedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.KickedPayload =
  com.maloy.proto.KickedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

