//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeplaybackActionPayload")
public inline fun playbackActionPayload(block: com.maloy.proto.PlaybackActionPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.PlaybackActionPayload =
  com.maloy.proto.PlaybackActionPayloadKt.Dsl._create(com.maloy.proto.Listentogether.PlaybackActionPayload.newBuilder()).apply { block() }._build()
public object PlaybackActionPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.PlaybackActionPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.PlaybackActionPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.PlaybackActionPayload = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>string track_id = 2;</code>
     */
    public var trackId: kotlin.String
      @JvmName("getTrackId")
      get() = _builder.getTrackId()
      @JvmName("setTrackId")
      set(value) {
        _builder.setTrackId(value)
      }
    /**
     * <code>string track_id = 2;</code>
     */
    public fun clearTrackId() {
      _builder.clearTrackId()
    }

    /**
     * <code>int64 position = 3;</code>
     */
    public var position: kotlin.Long
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * <code>int64 position = 3;</code>
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }

    /**
     * <code>.listentogether.TrackInfo track_info = 4;</code>
     */
    public var trackInfo: com.maloy.proto.Listentogether.TrackInfo
      @JvmName("getTrackInfo")
      get() = _builder.getTrackInfo()
      @JvmName("setTrackInfo")
      set(value) {
        _builder.setTrackInfo(value)
      }
    /**
     * <code>.listentogether.TrackInfo track_info = 4;</code>
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * <code>.listentogether.TrackInfo track_info = 4;</code>
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }

    /**
     * <code>bool insert_next = 5;</code>
     */
    public var insertNext: kotlin.Boolean
      @JvmName("getInsertNext")
      get() = _builder.getInsertNext()
      @JvmName("setInsertNext")
      set(value) {
        _builder.setInsertNext(value)
      }
    /**
     * <code>bool insert_next = 5;</code>
     */
    public fun clearInsertNext() {
      _builder.clearInsertNext()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class QueueProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .listentogether.TrackInfo queue = 6;</code>
     */
     public val queue: com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getQueueList()
      )
    /**
     * <code>repeated .listentogether.TrackInfo queue = 6;</code>
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.add(value: com.maloy.proto.Listentogether.TrackInfo) {
      _builder.addQueue(value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 6;</code>
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(value: com.maloy.proto.Listentogether.TrackInfo) {
      add(value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 6;</code>
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.addAll(values: kotlin.collections.Iterable<com.maloy.proto.Listentogether.TrackInfo>) {
      _builder.addAllQueue(values)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 6;</code>
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(values: kotlin.collections.Iterable<com.maloy.proto.Listentogether.TrackInfo>) {
      addAll(values)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 6;</code>
     * @param index The index to set the value at.
     * @param value The queue to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setQueue")
    public operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.set(index: kotlin.Int, value: com.maloy.proto.Listentogether.TrackInfo) {
      _builder.setQueue(index, value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.clear() {
      _builder.clearQueue()
    }


    /**
     * <code>string queue_title = 7;</code>
     */
    public var queueTitle: kotlin.String
      @JvmName("getQueueTitle")
      get() = _builder.getQueueTitle()
      @JvmName("setQueueTitle")
      set(value) {
        _builder.setQueueTitle(value)
      }
    /**
     * <code>string queue_title = 7;</code>
     */
    public fun clearQueueTitle() {
      _builder.clearQueueTitle()
    }

    /**
     * <code>float volume = 8;</code>
     */
    public var volume: kotlin.Float
      @JvmName("getVolume")
      get() = _builder.getVolume()
      @JvmName("setVolume")
      set(value) {
        _builder.setVolume(value)
      }
    /**
     * <code>float volume = 8;</code>
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }

    /**
     * <code>int64 server_time = 9;</code>
     */
    public var serverTime: kotlin.Long
      @JvmName("getServerTime")
      get() = _builder.getServerTime()
      @JvmName("setServerTime")
      set(value) {
        _builder.setServerTime(value)
      }
    /**
     * <code>int64 server_time = 9;</code>
     */
    public fun clearServerTime() {
      _builder.clearServerTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.PlaybackActionPayload.copy(block: com.maloy.proto.PlaybackActionPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.PlaybackActionPayload =
  com.maloy.proto.PlaybackActionPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.maloy.proto.Listentogether.PlaybackActionPayloadOrBuilder.trackInfoOrNull: com.maloy.proto.Listentogether.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

