//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializereconnectPayload")
public inline fun reconnectPayload(block: com.maloy.proto.ReconnectPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ReconnectPayload =
  com.maloy.proto.ReconnectPayloadKt.Dsl._create(com.maloy.proto.Listentogether.ReconnectPayload.newBuilder()).apply { block() }._build()
public object ReconnectPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.ReconnectPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.ReconnectPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.ReconnectPayload = _builder.build()

    /**
     * <code>string session_token = 1;</code>
     */
    public var sessionToken: kotlin.String
      @JvmName("getSessionToken")
      get() = _builder.getSessionToken()
      @JvmName("setSessionToken")
      set(value) {
        _builder.setSessionToken(value)
      }
    /**
     * <code>string session_token = 1;</code>
     */
    public fun clearSessionToken() {
      _builder.clearSessionToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.ReconnectPayload.copy(block: com.maloy.proto.ReconnectPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ReconnectPayload =
  com.maloy.proto.ReconnectPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

