//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializereconnectedPayload")
public inline fun reconnectedPayload(block: com.maloy.proto.ReconnectedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ReconnectedPayload =
  com.maloy.proto.ReconnectedPayloadKt.Dsl._create(com.maloy.proto.Listentogether.ReconnectedPayload.newBuilder()).apply { block() }._build()
public object ReconnectedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.ReconnectedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.ReconnectedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.ReconnectedPayload = _builder.build()

    /**
     * <code>string room_code = 1;</code>
     */
    public var roomCode: kotlin.String
      @JvmName("getRoomCode")
      get() = _builder.getRoomCode()
      @JvmName("setRoomCode")
      set(value) {
        _builder.setRoomCode(value)
      }
    /**
     * <code>string room_code = 1;</code>
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * <code>string user_id = 2;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 2;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * <code>.listentogether.RoomState state = 3;</code>
     */
    public var state: com.maloy.proto.Listentogether.RoomState
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    /**
     * <code>.listentogether.RoomState state = 3;</code>
     */
    public fun clearState() {
      _builder.clearState()
    }
    /**
     * <code>.listentogether.RoomState state = 3;</code>
     * @return Whether the state field is set.
     */
    public fun hasState(): kotlin.Boolean {
      return _builder.hasState()
    }

    /**
     * <code>bool is_host = 4;</code>
     */
    public var isHost: kotlin.Boolean
      @JvmName("getIsHost")
      get() = _builder.getIsHost()
      @JvmName("setIsHost")
      set(value) {
        _builder.setIsHost(value)
      }
    /**
     * <code>bool is_host = 4;</code>
     */
    public fun clearIsHost() {
      _builder.clearIsHost()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.ReconnectedPayload.copy(block: com.maloy.proto.ReconnectedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ReconnectedPayload =
  com.maloy.proto.ReconnectedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.maloy.proto.Listentogether.ReconnectedPayloadOrBuilder.stateOrNull: com.maloy.proto.Listentogether.RoomState?
  get() = if (hasState()) getState() else null

