//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializerejectJoinPayload")
public inline fun rejectJoinPayload(block: com.maloy.proto.RejectJoinPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.RejectJoinPayload =
  com.maloy.proto.RejectJoinPayloadKt.Dsl._create(com.maloy.proto.Listentogether.RejectJoinPayload.newBuilder()).apply { block() }._build()
public object RejectJoinPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.RejectJoinPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.RejectJoinPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.RejectJoinPayload = _builder.build()

    /**
     * <code>string user_id = 1;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 1;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * <code>string reason = 2;</code>
     */
    public var reason: kotlin.String
      @JvmName("getReason")
      get() = _builder.getReason()
      @JvmName("setReason")
      set(value) {
        _builder.setReason(value)
      }
    /**
     * <code>string reason = 2;</code>
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.RejectJoinPayload.copy(block: com.maloy.proto.RejectJoinPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.RejectJoinPayload =
  com.maloy.proto.RejectJoinPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

