//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeroomCreatedPayload")
public inline fun roomCreatedPayload(block: com.maloy.proto.RoomCreatedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.RoomCreatedPayload =
  com.maloy.proto.RoomCreatedPayloadKt.Dsl._create(com.maloy.proto.Listentogether.RoomCreatedPayload.newBuilder()).apply { block() }._build()
public object RoomCreatedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.RoomCreatedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.RoomCreatedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.RoomCreatedPayload = _builder.build()

    /**
     * <code>string room_code = 1;</code>
     */
    public var roomCode: kotlin.String
      @JvmName("getRoomCode")
      get() = _builder.getRoomCode()
      @JvmName("setRoomCode")
      set(value) {
        _builder.setRoomCode(value)
      }
    /**
     * <code>string room_code = 1;</code>
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * <code>string user_id = 2;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 2;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * <code>string session_token = 3;</code>
     */
    public var sessionToken: kotlin.String
      @JvmName("getSessionToken")
      get() = _builder.getSessionToken()
      @JvmName("setSessionToken")
      set(value) {
        _builder.setSessionToken(value)
      }
    /**
     * <code>string session_token = 3;</code>
     */
    public fun clearSessionToken() {
      _builder.clearSessionToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.RoomCreatedPayload.copy(block: com.maloy.proto.RoomCreatedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.RoomCreatedPayload =
  com.maloy.proto.RoomCreatedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

