//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeroomState")
public inline fun roomState(block: com.maloy.proto.RoomStateKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.RoomState =
  com.maloy.proto.RoomStateKt.Dsl._create(com.maloy.proto.Listentogether.RoomState.newBuilder()).apply { block() }._build()
public object RoomStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.RoomState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.RoomState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.RoomState = _builder.build()

    /**
     * <code>string room_code = 1;</code>
     */
    public var roomCode: kotlin.String
      @JvmName("getRoomCode")
      get() = _builder.getRoomCode()
      @JvmName("setRoomCode")
      set(value) {
        _builder.setRoomCode(value)
      }
    /**
     * <code>string room_code = 1;</code>
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * <code>string host_id = 2;</code>
     */
    public var hostId: kotlin.String
      @JvmName("getHostId")
      get() = _builder.getHostId()
      @JvmName("setHostId")
      set(value) {
        _builder.setHostId(value)
      }
    /**
     * <code>string host_id = 2;</code>
     */
    public fun clearHostId() {
      _builder.clearHostId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UsersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .listentogether.UserInfo users = 3;</code>
     */
     public val users: com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.UserInfo, UsersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getUsersList()
      )
    /**
     * <code>repeated .listentogether.UserInfo users = 3;</code>
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addUsers")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.UserInfo, UsersProxy>.add(value: com.maloy.proto.Listentogether.UserInfo) {
      _builder.addUsers(value)
    }
    /**
     * <code>repeated .listentogether.UserInfo users = 3;</code>
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.UserInfo, UsersProxy>.plusAssign(value: com.maloy.proto.Listentogether.UserInfo) {
      add(value)
    }
    /**
     * <code>repeated .listentogether.UserInfo users = 3;</code>
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllUsers")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.UserInfo, UsersProxy>.addAll(values: kotlin.collections.Iterable<com.maloy.proto.Listentogether.UserInfo>) {
      _builder.addAllUsers(values)
    }
    /**
     * <code>repeated .listentogether.UserInfo users = 3;</code>
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.UserInfo, UsersProxy>.plusAssign(values: kotlin.collections.Iterable<com.maloy.proto.Listentogether.UserInfo>) {
      addAll(values)
    }
    /**
     * <code>repeated .listentogether.UserInfo users = 3;</code>
     * @param index The index to set the value at.
     * @param value The users to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setUsers")
    public operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.UserInfo, UsersProxy>.set(index: kotlin.Int, value: com.maloy.proto.Listentogether.UserInfo) {
      _builder.setUsers(index, value)
    }
    /**
     * <code>repeated .listentogether.UserInfo users = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearUsers")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.UserInfo, UsersProxy>.clear() {
      _builder.clearUsers()
    }


    /**
     * <code>.listentogether.TrackInfo current_track = 4;</code>
     */
    public var currentTrack: com.maloy.proto.Listentogether.TrackInfo
      @JvmName("getCurrentTrack")
      get() = _builder.getCurrentTrack()
      @JvmName("setCurrentTrack")
      set(value) {
        _builder.setCurrentTrack(value)
      }
    /**
     * <code>.listentogether.TrackInfo current_track = 4;</code>
     */
    public fun clearCurrentTrack() {
      _builder.clearCurrentTrack()
    }
    /**
     * <code>.listentogether.TrackInfo current_track = 4;</code>
     * @return Whether the currentTrack field is set.
     */
    public fun hasCurrentTrack(): kotlin.Boolean {
      return _builder.hasCurrentTrack()
    }

    /**
     * <code>bool is_playing = 5;</code>
     */
    public var isPlaying: kotlin.Boolean
      @JvmName("getIsPlaying")
      get() = _builder.getIsPlaying()
      @JvmName("setIsPlaying")
      set(value) {
        _builder.setIsPlaying(value)
      }
    /**
     * <code>bool is_playing = 5;</code>
     */
    public fun clearIsPlaying() {
      _builder.clearIsPlaying()
    }

    /**
     * <code>int64 position = 6;</code>
     */
    public var position: kotlin.Long
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * <code>int64 position = 6;</code>
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }

    /**
     * <code>int64 last_update = 7;</code>
     */
    public var lastUpdate: kotlin.Long
      @JvmName("getLastUpdate")
      get() = _builder.getLastUpdate()
      @JvmName("setLastUpdate")
      set(value) {
        _builder.setLastUpdate(value)
      }
    /**
     * <code>int64 last_update = 7;</code>
     */
    public fun clearLastUpdate() {
      _builder.clearLastUpdate()
    }

    /**
     * <code>float volume = 8;</code>
     */
    public var volume: kotlin.Float
      @JvmName("getVolume")
      get() = _builder.getVolume()
      @JvmName("setVolume")
      set(value) {
        _builder.setVolume(value)
      }
    /**
     * <code>float volume = 8;</code>
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class QueueProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .listentogether.TrackInfo queue = 9;</code>
     */
     public val queue: com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getQueueList()
      )
    /**
     * <code>repeated .listentogether.TrackInfo queue = 9;</code>
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.add(value: com.maloy.proto.Listentogether.TrackInfo) {
      _builder.addQueue(value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 9;</code>
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(value: com.maloy.proto.Listentogether.TrackInfo) {
      add(value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 9;</code>
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.addAll(values: kotlin.collections.Iterable<com.maloy.proto.Listentogether.TrackInfo>) {
      _builder.addAllQueue(values)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 9;</code>
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(values: kotlin.collections.Iterable<com.maloy.proto.Listentogether.TrackInfo>) {
      addAll(values)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 9;</code>
     * @param index The index to set the value at.
     * @param value The queue to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setQueue")
    public operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.set(index: kotlin.Int, value: com.maloy.proto.Listentogether.TrackInfo) {
      _builder.setQueue(index, value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.clear() {
      _builder.clearQueue()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.RoomState.copy(block: com.maloy.proto.RoomStateKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.RoomState =
  com.maloy.proto.RoomStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.maloy.proto.Listentogether.RoomStateOrBuilder.currentTrackOrNull: com.maloy.proto.Listentogether.TrackInfo?
  get() = if (hasCurrentTrack()) getCurrentTrack() else null

