//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeserverCapabilities")
public inline fun serverCapabilities(block: com.maloy.proto.ServerCapabilitiesKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ServerCapabilities =
  com.maloy.proto.ServerCapabilitiesKt.Dsl._create(com.maloy.proto.Listentogether.ServerCapabilities.newBuilder()).apply { block() }._build()
public object ServerCapabilitiesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.ServerCapabilities.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.ServerCapabilities.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.ServerCapabilities = _builder.build()

    /**
     * <code>bool supports_protobuf = 1;</code>
     */
    public var supportsProtobuf: kotlin.Boolean
      @JvmName("getSupportsProtobuf")
      get() = _builder.getSupportsProtobuf()
      @JvmName("setSupportsProtobuf")
      set(value) {
        _builder.setSupportsProtobuf(value)
      }
    /**
     * <code>bool supports_protobuf = 1;</code>
     */
    public fun clearSupportsProtobuf() {
      _builder.clearSupportsProtobuf()
    }

    /**
     * <code>bool supports_compression = 2;</code>
     */
    public var supportsCompression: kotlin.Boolean
      @JvmName("getSupportsCompression")
      get() = _builder.getSupportsCompression()
      @JvmName("setSupportsCompression")
      set(value) {
        _builder.setSupportsCompression(value)
      }
    /**
     * <code>bool supports_compression = 2;</code>
     */
    public fun clearSupportsCompression() {
      _builder.clearSupportsCompression()
    }

    /**
     * <code>string server_version = 3;</code>
     */
    public var serverVersion: kotlin.String
      @JvmName("getServerVersion")
      get() = _builder.getServerVersion()
      @JvmName("setServerVersion")
      set(value) {
        _builder.setServerVersion(value)
      }
    /**
     * <code>string server_version = 3;</code>
     */
    public fun clearServerVersion() {
      _builder.clearServerVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.ServerCapabilities.copy(block: com.maloy.proto.ServerCapabilitiesKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.ServerCapabilities =
  com.maloy.proto.ServerCapabilitiesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

