//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializesuggestTrackPayload")
public inline fun suggestTrackPayload(block: com.maloy.proto.SuggestTrackPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SuggestTrackPayload =
  com.maloy.proto.SuggestTrackPayloadKt.Dsl._create(com.maloy.proto.Listentogether.SuggestTrackPayload.newBuilder()).apply { block() }._build()
public object SuggestTrackPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.SuggestTrackPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.SuggestTrackPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.SuggestTrackPayload = _builder.build()

    /**
     * <code>.listentogether.TrackInfo track_info = 1;</code>
     */
    public var trackInfo: com.maloy.proto.Listentogether.TrackInfo
      @JvmName("getTrackInfo")
      get() = _builder.getTrackInfo()
      @JvmName("setTrackInfo")
      set(value) {
        _builder.setTrackInfo(value)
      }
    /**
     * <code>.listentogether.TrackInfo track_info = 1;</code>
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * <code>.listentogether.TrackInfo track_info = 1;</code>
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.SuggestTrackPayload.copy(block: com.maloy.proto.SuggestTrackPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SuggestTrackPayload =
  com.maloy.proto.SuggestTrackPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.maloy.proto.Listentogether.SuggestTrackPayloadOrBuilder.trackInfoOrNull: com.maloy.proto.Listentogether.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

