//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializesuggestionApprovedPayload")
public inline fun suggestionApprovedPayload(block: com.maloy.proto.SuggestionApprovedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SuggestionApprovedPayload =
  com.maloy.proto.SuggestionApprovedPayloadKt.Dsl._create(com.maloy.proto.Listentogether.SuggestionApprovedPayload.newBuilder()).apply { block() }._build()
public object SuggestionApprovedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.SuggestionApprovedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.SuggestionApprovedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.SuggestionApprovedPayload = _builder.build()

    /**
     * <code>string suggestion_id = 1;</code>
     */
    public var suggestionId: kotlin.String
      @JvmName("getSuggestionId")
      get() = _builder.getSuggestionId()
      @JvmName("setSuggestionId")
      set(value) {
        _builder.setSuggestionId(value)
      }
    /**
     * <code>string suggestion_id = 1;</code>
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }

    /**
     * <code>.listentogether.TrackInfo track_info = 2;</code>
     */
    public var trackInfo: com.maloy.proto.Listentogether.TrackInfo
      @JvmName("getTrackInfo")
      get() = _builder.getTrackInfo()
      @JvmName("setTrackInfo")
      set(value) {
        _builder.setTrackInfo(value)
      }
    /**
     * <code>.listentogether.TrackInfo track_info = 2;</code>
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * <code>.listentogether.TrackInfo track_info = 2;</code>
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.SuggestionApprovedPayload.copy(block: com.maloy.proto.SuggestionApprovedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SuggestionApprovedPayload =
  com.maloy.proto.SuggestionApprovedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.maloy.proto.Listentogether.SuggestionApprovedPayloadOrBuilder.trackInfoOrNull: com.maloy.proto.Listentogether.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

