//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializesuggestionReceivedPayload")
public inline fun suggestionReceivedPayload(block: com.maloy.proto.SuggestionReceivedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SuggestionReceivedPayload =
  com.maloy.proto.SuggestionReceivedPayloadKt.Dsl._create(com.maloy.proto.Listentogether.SuggestionReceivedPayload.newBuilder()).apply { block() }._build()
public object SuggestionReceivedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.SuggestionReceivedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.SuggestionReceivedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.SuggestionReceivedPayload = _builder.build()

    /**
     * <code>string suggestion_id = 1;</code>
     */
    public var suggestionId: kotlin.String
      @JvmName("getSuggestionId")
      get() = _builder.getSuggestionId()
      @JvmName("setSuggestionId")
      set(value) {
        _builder.setSuggestionId(value)
      }
    /**
     * <code>string suggestion_id = 1;</code>
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }

    /**
     * <code>string from_user_id = 2;</code>
     */
    public var fromUserId: kotlin.String
      @JvmName("getFromUserId")
      get() = _builder.getFromUserId()
      @JvmName("setFromUserId")
      set(value) {
        _builder.setFromUserId(value)
      }
    /**
     * <code>string from_user_id = 2;</code>
     */
    public fun clearFromUserId() {
      _builder.clearFromUserId()
    }

    /**
     * <code>string from_username = 3;</code>
     */
    public var fromUsername: kotlin.String
      @JvmName("getFromUsername")
      get() = _builder.getFromUsername()
      @JvmName("setFromUsername")
      set(value) {
        _builder.setFromUsername(value)
      }
    /**
     * <code>string from_username = 3;</code>
     */
    public fun clearFromUsername() {
      _builder.clearFromUsername()
    }

    /**
     * <code>.listentogether.TrackInfo track_info = 4;</code>
     */
    public var trackInfo: com.maloy.proto.Listentogether.TrackInfo
      @JvmName("getTrackInfo")
      get() = _builder.getTrackInfo()
      @JvmName("setTrackInfo")
      set(value) {
        _builder.setTrackInfo(value)
      }
    /**
     * <code>.listentogether.TrackInfo track_info = 4;</code>
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * <code>.listentogether.TrackInfo track_info = 4;</code>
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.SuggestionReceivedPayload.copy(block: com.maloy.proto.SuggestionReceivedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SuggestionReceivedPayload =
  com.maloy.proto.SuggestionReceivedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.maloy.proto.Listentogether.SuggestionReceivedPayloadOrBuilder.trackInfoOrNull: com.maloy.proto.Listentogether.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

