//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializesuggestionRejectedPayload")
public inline fun suggestionRejectedPayload(block: com.maloy.proto.SuggestionRejectedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SuggestionRejectedPayload =
  com.maloy.proto.SuggestionRejectedPayloadKt.Dsl._create(com.maloy.proto.Listentogether.SuggestionRejectedPayload.newBuilder()).apply { block() }._build()
public object SuggestionRejectedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.SuggestionRejectedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.SuggestionRejectedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.SuggestionRejectedPayload = _builder.build()

    /**
     * <code>string suggestion_id = 1;</code>
     */
    public var suggestionId: kotlin.String
      @JvmName("getSuggestionId")
      get() = _builder.getSuggestionId()
      @JvmName("setSuggestionId")
      set(value) {
        _builder.setSuggestionId(value)
      }
    /**
     * <code>string suggestion_id = 1;</code>
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }

    /**
     * <code>string reason = 2;</code>
     */
    public var reason: kotlin.String
      @JvmName("getReason")
      get() = _builder.getReason()
      @JvmName("setReason")
      set(value) {
        _builder.setReason(value)
      }
    /**
     * <code>string reason = 2;</code>
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.SuggestionRejectedPayload.copy(block: com.maloy.proto.SuggestionRejectedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SuggestionRejectedPayload =
  com.maloy.proto.SuggestionRejectedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

