//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializesyncStatePayload")
public inline fun syncStatePayload(block: com.maloy.proto.SyncStatePayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SyncStatePayload =
  com.maloy.proto.SyncStatePayloadKt.Dsl._create(com.maloy.proto.Listentogether.SyncStatePayload.newBuilder()).apply { block() }._build()
public object SyncStatePayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.SyncStatePayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.SyncStatePayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.SyncStatePayload = _builder.build()

    /**
     * <code>.listentogether.TrackInfo current_track = 1;</code>
     */
    public var currentTrack: com.maloy.proto.Listentogether.TrackInfo
      @JvmName("getCurrentTrack")
      get() = _builder.getCurrentTrack()
      @JvmName("setCurrentTrack")
      set(value) {
        _builder.setCurrentTrack(value)
      }
    /**
     * <code>.listentogether.TrackInfo current_track = 1;</code>
     */
    public fun clearCurrentTrack() {
      _builder.clearCurrentTrack()
    }
    /**
     * <code>.listentogether.TrackInfo current_track = 1;</code>
     * @return Whether the currentTrack field is set.
     */
    public fun hasCurrentTrack(): kotlin.Boolean {
      return _builder.hasCurrentTrack()
    }

    /**
     * <code>bool is_playing = 2;</code>
     */
    public var isPlaying: kotlin.Boolean
      @JvmName("getIsPlaying")
      get() = _builder.getIsPlaying()
      @JvmName("setIsPlaying")
      set(value) {
        _builder.setIsPlaying(value)
      }
    /**
     * <code>bool is_playing = 2;</code>
     */
    public fun clearIsPlaying() {
      _builder.clearIsPlaying()
    }

    /**
     * <code>int64 position = 3;</code>
     */
    public var position: kotlin.Long
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * <code>int64 position = 3;</code>
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }

    /**
     * <code>int64 last_update = 4;</code>
     */
    public var lastUpdate: kotlin.Long
      @JvmName("getLastUpdate")
      get() = _builder.getLastUpdate()
      @JvmName("setLastUpdate")
      set(value) {
        _builder.setLastUpdate(value)
      }
    /**
     * <code>int64 last_update = 4;</code>
     */
    public fun clearLastUpdate() {
      _builder.clearLastUpdate()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class QueueProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .listentogether.TrackInfo queue = 5;</code>
     */
     public val queue: com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getQueueList()
      )
    /**
     * <code>repeated .listentogether.TrackInfo queue = 5;</code>
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.add(value: com.maloy.proto.Listentogether.TrackInfo) {
      _builder.addQueue(value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 5;</code>
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(value: com.maloy.proto.Listentogether.TrackInfo) {
      add(value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 5;</code>
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.addAll(values: kotlin.collections.Iterable<com.maloy.proto.Listentogether.TrackInfo>) {
      _builder.addAllQueue(values)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 5;</code>
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(values: kotlin.collections.Iterable<com.maloy.proto.Listentogether.TrackInfo>) {
      addAll(values)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 5;</code>
     * @param index The index to set the value at.
     * @param value The queue to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setQueue")
    public operator fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.set(index: kotlin.Int, value: com.maloy.proto.Listentogether.TrackInfo) {
      _builder.setQueue(index, value)
    }
    /**
     * <code>repeated .listentogether.TrackInfo queue = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearQueue")
    public fun com.google.protobuf.kotlin.DslList<com.maloy.proto.Listentogether.TrackInfo, QueueProxy>.clear() {
      _builder.clearQueue()
    }


    /**
     * <code>float volume = 6;</code>
     */
    public var volume: kotlin.Float
      @JvmName("getVolume")
      get() = _builder.getVolume()
      @JvmName("setVolume")
      set(value) {
        _builder.setVolume(value)
      }
    /**
     * <code>float volume = 6;</code>
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.SyncStatePayload.copy(block: com.maloy.proto.SyncStatePayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.SyncStatePayload =
  com.maloy.proto.SyncStatePayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.maloy.proto.Listentogether.SyncStatePayloadOrBuilder.currentTrackOrNull: com.maloy.proto.Listentogether.TrackInfo?
  get() = if (hasCurrentTrack()) getCurrentTrack() else null

