//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializetrackInfo")
public inline fun trackInfo(block: com.maloy.proto.TrackInfoKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.TrackInfo =
  com.maloy.proto.TrackInfoKt.Dsl._create(com.maloy.proto.Listentogether.TrackInfo.newBuilder()).apply { block() }._build()
public object TrackInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.TrackInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.TrackInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.TrackInfo = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string title = 2;</code>
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * <code>string title = 2;</code>
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * <code>string artist = 3;</code>
     */
    public var artist: kotlin.String
      @JvmName("getArtist")
      get() = _builder.getArtist()
      @JvmName("setArtist")
      set(value) {
        _builder.setArtist(value)
      }
    /**
     * <code>string artist = 3;</code>
     */
    public fun clearArtist() {
      _builder.clearArtist()
    }

    /**
     * <code>string album = 4;</code>
     */
    public var album: kotlin.String
      @JvmName("getAlbum")
      get() = _builder.getAlbum()
      @JvmName("setAlbum")
      set(value) {
        _builder.setAlbum(value)
      }
    /**
     * <code>string album = 4;</code>
     */
    public fun clearAlbum() {
      _builder.clearAlbum()
    }

    /**
     * <code>int64 duration = 5;</code>
     */
    public var duration: kotlin.Long
      @JvmName("getDuration")
      get() = _builder.getDuration()
      @JvmName("setDuration")
      set(value) {
        _builder.setDuration(value)
      }
    /**
     * <code>int64 duration = 5;</code>
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }

    /**
     * <code>string thumbnail = 6;</code>
     */
    public var thumbnail: kotlin.String
      @JvmName("getThumbnail")
      get() = _builder.getThumbnail()
      @JvmName("setThumbnail")
      set(value) {
        _builder.setThumbnail(value)
      }
    /**
     * <code>string thumbnail = 6;</code>
     */
    public fun clearThumbnail() {
      _builder.clearThumbnail()
    }

    /**
     * <code>string suggested_by = 7;</code>
     */
    public var suggestedBy: kotlin.String
      @JvmName("getSuggestedBy")
      get() = _builder.getSuggestedBy()
      @JvmName("setSuggestedBy")
      set(value) {
        _builder.setSuggestedBy(value)
      }
    /**
     * <code>string suggested_by = 7;</code>
     */
    public fun clearSuggestedBy() {
      _builder.clearSuggestedBy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.TrackInfo.copy(block: com.maloy.proto.TrackInfoKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.TrackInfo =
  com.maloy.proto.TrackInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

