//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializetransferHostPayload")
public inline fun transferHostPayload(block: com.maloy.proto.TransferHostPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.TransferHostPayload =
  com.maloy.proto.TransferHostPayloadKt.Dsl._create(com.maloy.proto.Listentogether.TransferHostPayload.newBuilder()).apply { block() }._build()
public object TransferHostPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.TransferHostPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.TransferHostPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.TransferHostPayload = _builder.build()

    /**
     * <code>string new_host_id = 1;</code>
     */
    public var newHostId: kotlin.String
      @JvmName("getNewHostId")
      get() = _builder.getNewHostId()
      @JvmName("setNewHostId")
      set(value) {
        _builder.setNewHostId(value)
      }
    /**
     * <code>string new_host_id = 1;</code>
     */
    public fun clearNewHostId() {
      _builder.clearNewHostId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.TransferHostPayload.copy(block: com.maloy.proto.TransferHostPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.TransferHostPayload =
  com.maloy.proto.TransferHostPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

