//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeuserJoinedPayload")
public inline fun userJoinedPayload(block: com.maloy.proto.UserJoinedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.UserJoinedPayload =
  com.maloy.proto.UserJoinedPayloadKt.Dsl._create(com.maloy.proto.Listentogether.UserJoinedPayload.newBuilder()).apply { block() }._build()
public object UserJoinedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.UserJoinedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.UserJoinedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.UserJoinedPayload = _builder.build()

    /**
     * <code>string user_id = 1;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 1;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * <code>string username = 2;</code>
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * <code>string username = 2;</code>
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.UserJoinedPayload.copy(block: com.maloy.proto.UserJoinedPayloadKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.UserJoinedPayload =
  com.maloy.proto.UserJoinedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

