//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: listentogether.proto

package com.maloy.proto;

@kotlin.jvm.JvmName("-initializeuserInfo")
public inline fun userInfo(block: com.maloy.proto.UserInfoKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.UserInfo =
  com.maloy.proto.UserInfoKt.Dsl._create(com.maloy.proto.Listentogether.UserInfo.newBuilder()).apply { block() }._build()
public object UserInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.maloy.proto.Listentogether.UserInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.maloy.proto.Listentogether.UserInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.maloy.proto.Listentogether.UserInfo = _builder.build()

    /**
     * <code>string user_id = 1;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 1;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * <code>string username = 2;</code>
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * <code>string username = 2;</code>
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * <code>bool is_host = 3;</code>
     */
    public var isHost: kotlin.Boolean
      @JvmName("getIsHost")
      get() = _builder.getIsHost()
      @JvmName("setIsHost")
      set(value) {
        _builder.setIsHost(value)
      }
    /**
     * <code>bool is_host = 3;</code>
     */
    public fun clearIsHost() {
      _builder.clearIsHost()
    }

    /**
     * <code>bool is_connected = 4;</code>
     */
    public var isConnected: kotlin.Boolean
      @JvmName("getIsConnected")
      get() = _builder.getIsConnected()
      @JvmName("setIsConnected")
      set(value) {
        _builder.setIsConnected(value)
      }
    /**
     * <code>bool is_connected = 4;</code>
     */
    public fun clearIsConnected() {
      _builder.clearIsConnected()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.maloy.proto.Listentogether.UserInfo.copy(block: com.maloy.proto.UserInfoKt.Dsl.() -> kotlin.Unit): com.maloy.proto.Listentogether.UserInfo =
  com.maloy.proto.UserInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

