name: Build debug APK
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decode google-services.json
        run: echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d >> app/google-services.json

      - name: Decode Keystore
        run: echo ${{ secrets.KEYSTORE }} | base64 -d >> app/music-debug.jks

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

      - name: Build debug APK and run jvm tests
        run: ./gradlew assembleDebug lintFossDebug testFossDebugUnitTest --stacktrace -DskipFormatKtlint
        env:
          MUSIC_DEBUG_KEYSTORE_FILE: 'music-debug.jks'
          MUSIC_DEBUG_SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          MUSIC_DEBUG_SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/foss/debug/*.apk
